### ISSUE TITLE
Transfer to `sphinx-contrib`?

### ISSUE THREAD

**Issue by Peque** [sphinx-contrib/emojicodes#1]
@chintal Maybe it is useful for others. I could keep maintenance of the repo within the organization if you allow me.

I have [this too](https://github.com/Peque/sphinxcadquery), but maybe it is too specific.

**Comment by chintal** [comment]
@Peque I would say it's probably useful to someone or the other. I find it more convenient to add my extensions onto sphinx-contrib, even if no one else I know uses that particular extension. At the very least, in case someone does come looking for what I have they can find it on sphinx-contrib more easily. Also, since sphinxcontrib is a python namespace, it makes it less likely that someone will accidentally put in something with the same name (as long as they at least check sphinx-contrib, even if they don't search all extensions available everywhere). It is your choice, what you want to do with them (for both repositories).

@stephenfin Might I suggest adding @Peque as a member on sphinx-contrib so that they may transfer the repository there? I tag you because you were the one who e-mailed the extension authors originally. Let me know if there is someone else maintaining the list now.

**Comment by chintal** [comment]
Also @dhellmann ^

**Comment by dhellmann** [comment]
I have invited @Peque to be a member of sphinx-contrib. I think that will let us start the repo transfer, although someone else might need to approve it. After it moves, I can ensure @Peque has write access to it again.

**Comment by Peque** [comment]
@chintal @dhellmann Thanks, it seems the transfer was pretty smooth.

Is the repository name correct? (I renamed it to `emojicodes`)

I guess there is some work to do now to change the project's namespace and to be able to upload it under the sphinx-contrib namespace to PyPI too. Would you give me permissions for that or is it something that someone else in the organization is expected to do?

**Comment by dhellmann** [comment]
> @chintal @dhellmann Thanks, it seems the transfer was pretty smooth.
> 
> Is the repository name correct? (I renamed it to `emojicodes` because having `sphinx` in its name would be redundant now that it is under `sphinx-contrib` organization)

That makes sense.

> I guess there is some work to do now to change the project's namespace and to be able to upload it under the sphinx-contrib namespace to PyPI too. Would you give me permissions for that or is it something that someone else in the organization is expected to do?

There aren't really "namespaces" on PyPI. Each package just has its own name. So, if you're going to rename the package you will want to register it under the new name, which will happen automatically when you upload the first release.

**Comment by stephenfin** [comment]
> @chintal @dhellmann Thanks, it seems the transfer was pretty smooth.
> 
> Is the repository name correct? (I renamed it to `emojicodes` because having `sphinx` in its name would be redundant now that it is under `sphinx-contrib` organization)

As dhellmann noted, this makes sense.

> I guess there is some work to do now to change the project's namespace and to be able to upload it under the sphinx-contrib namespace to PyPI too. Would you give me permissions for that or is it something that someone else in the organization is expected to do?

I wouldn't personally change the package name without good reason. PyPI doesn't support groups yet so there's no sphinx-contrib group. There is a sphinx-contrib user, which I own, but that's just there for packages in the sphinx-contrib namespace that the original owner doesn't want to maintain anymore. As a result, if you want to make releases, the owner of the package on PyPI would have to add you as a maintainer in order for you to make a release. I'm not sure which of you is that person so I'll let you figure that out between you :smile:

**Comment by Peque** [comment]
Closing this. I will leave the package name as-is then. :blush:

I always assumed namespaces existed in PyPI (never bothered to verify my assumption though). :joy:

**Comment by Peque** [comment]
@chintal Do you know how could I activate the Read the Docs webhook in this repo?

![Screenshot from 2019-06-06 00-41-44](https://user-images.githubusercontent.com/526577/58995372-415e9b80-87f4-11e9-9642-924891be253d.png)

Also, how can I edit the project's description and link? (I don't see the "edit" button on the right)

![Screenshot from 2019-06-06 00-45-03](https://user-images.githubusercontent.com/526577/58995408-66eba500-87f4-11e9-8cd4-266853c74d01.png)

**Comment by dhellmann** [comment]
@Peque I have made you an admin on this repository. If you reload the settings page, you should see those options now.

**Comment by Peque** [comment]
@dhellmann Thanks! :blush:
