### ISSUE TITLE
How to use it inside table ?

### ISSUE THREAD

**Issue by Milerius** [sphinx-contrib/emojicodes#10]
I try to use emoji inside rst table but i got an error: 'WARNING: Malformed table.'

**Comment by Peque** [comment]
Please, can you provide a reproducible case? (i.e.: the code that yields that error). :blush:

**Comment by Milerius** [comment]
Working now sorry, mistake from me

**Comment by rubenflamshepherd** [comment]
For others that stumble across this, I was having this same issue but was using the semicolon notation (For example: `:no_entry:`). What worked for me was copying and pasting the actual emoji glyph into my IDE. See example below:

<img width="119" alt="Screen Shot 2020-05-09 at 5 16 32 PM" src="https://user-images.githubusercontent.com/10005416/81485130-db0aa600-9218-11ea-9758-8f5186c17855.png">
