### ISSUE TITLE
Document list of supported emoji styles

### ISSUE THREAD

**Issue by honzajavorek** [sphinx-contrib/emojicodes#11]
The README mentions

```
sphinxemoji_style = ...
```

but there's no list of what styles are supported. I'm willing to send a PR if I get to know where to learn the supported styles.

**Comment by Peque** [comment]
Thanks for opening this issue! :blush: 

Currently the list of supported styles has length 1. :stuck_out_tongue_winking_eye:

Maybe it would not be a bad idea to mention that in the README/docs.

Feel free to contribute other Emoji styles if you want!

Relevant code:

https://github.com/sphinx-contrib/emojicodes/blob/44640719fd1dfd98ea7a75b166e8cd47a3b14a60/sphinxemoji/sphinxemoji.py#L58-L62
