### ISSUE TITLE
RemovedInSphinx40Warning: The app.add_javascript() is deprecated

### ISSUE THREAD

**Issue by domdfcoding** [sphinx-contrib/emojicodes#19]
Hi,

`sphinxemoji.py` calls `app.add_javascript()` three times on lines 60, 61 and 62 (right at the bottom of the file). This function was renamed to `add_js_file` in Sphinx version 1.8 and the old version will be removed in Sphinx 4.0. 

Currently Sphinx only throws a warning about this but eventually it will break. It looks like the two functions have the same syntax, so the fix should be as simple as changing the name in `sphinxemoji.py`.

See [https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file) for a bit more info.

**Comment by Peque** [comment]
@domdfcoding Thanks for reporting! Would you mind opening a pull request with the change? :blush:

**Comment by domdfcoding** [comment]
Done. 

I realised it's actually only two instances of `app.add_javascript()`; the third one is `app.add_stylesheet()`, which becomes `app.add_css_file()`.
