### ISSUE TITLE
Document coding scheme used

### ISSUE THREAD

**Issue by lordmauve** [sphinx-contrib/emojicodes#2]
I couldn't find a reference for the codes used other than [the source file itself](https://github.com/sphinx-contrib/emojicodes/blob/master/sphinxemoji/codes.json).

Where are the codes from? Is it just https://www.webfx.com/tools/emoji-cheat-sheet/?

Some codes are missing compared to those supported by GitHub (https://api.github.com/emojis), which is worth knowing.

Perhaps the README contain an auto-generated table (as per https://github.com/ikatyang/emoji-cheat-sheet)?

**Comment by Peque** [comment]
@lordmauve Thanks for your feedback.

The codes come from [Gitlab CE mirror](https://github.com/gitlabhq/gitlabhq). You can see [the script to update emoji codes in this repo](https://github.com/sphinx-contrib/emojicodes/blob/master/sphinxemoji/utils.py).

Which emoji codes are you missing from the currently available? I find it surprising that there are any missing.

Updating the README file with this information may be a good idea. I may create a page in Read the Docs to display all emoji codes (emoji-cheat-sheet-like).

**Comment by Peque** [comment]
@lordmauve You can now find a list of the supported emoji:

https://sphinxemojicodes.readthedocs.io/

It is now also linked from the README file.

**Comment by lordmauve** [comment]
Great! Very helpful, thanks. (I wrote a blog post recommending this, for fun, at work :-)

I was just comparing with the GitHub emoji list by eyeball and there are some missing immediately: :+1:, :-1:, :first_place_medal: etc

**Comment by Peque** [comment]
@lordmauve Indeed! I was missing some aliases. `:+1:` and `:-1:` should be available in version 0.1.1 (they were named only `:thumbsup:` and `:thumbsdown:` before).

:1st_place_medal: is `:first_place:` (or `:first_place_medal:` after the aliases addition).

Do you miss any other?

**Comment by Peque** [comment]
Closing this.

I opened an issue in this project to note which are missing (compared to GitHub): https://github.com/sphinx-contrib/emojicodes/issues/4

@lordmauve Thanks for reporting! :blush:
