### ISSUE TITLE
Get rid of asterisk warnings

### ISSUE THREAD

**Issue by Peque** [sphinx-contrib/emojicodes#24]
See: 

- https://github.com/sphinx-doc/sphinx/issues/8276
- https://stackoverflow.com/questions/64187781

**Comment by Gerald-Izuchukwu** [comment]
where are we supposed to get rid of the asterisk from?

**Comment by Peque** [comment]
@Gerald-Izuchukwu You can read the linked websites above to get some context.

The goal is to get rid of the warning thrown when this repository's documentation is built. Or, actually, when any documentation that uses this Sphinx extension will throw if they use `|:asterisk:|`.
