### ISSUE TITLE
Please include the LICENSE file in the pypi tar

### ISSUE THREAD

**Issue by sanjayankur31** [sphinx-contrib/emojicodes#38]
Hello,

I'm packaging sphinxmoji for inclusion in the Fedora Linux repositories.

https://bugzilla.redhat.com/show_bug.cgi?id=2010053

During the review, we observed that the pypi tar does not include the LICENSE file. The BSD license requires that it be included with both source code and binary forms.  Would it be possible to include it there please?

Thanks very much,

**Comment by Peque** [comment]
@sanjayankur31 As a Fedora user myself, I am happy to hear the news! :blush: 

Feel free to contribute the required changes to add the LICENSE file to the `.tar` release.

**Comment by Peque** [comment]
@sanjayankur31 This should be fixed after https://github.com/sphinx-contrib/emojicodes/pull/44. :blush:
