### ISSUE TITLE
Guidance to add it to readthedocs

### ISSUE THREAD

**Issue by gwilku** [sphinx-contrib/emojicodes#43]
Hi,

Is there a chance for a step-by-step manual on how to add this to one's project in readthedocs? I followed the instructions, I can see RTD installs sphinxemoji, I have it in extensions, build goes through successfully, however no replacement happens and I see |:rawemojitexthere:| instead of the images/glyphs. What am I missing?

**Comment by Peque** [comment]
@gwilku Are you using `.rst` or `.md` files in your documentation?

If you are using Markdown, I think this is relevant: https://github.com/sphinx-contrib/emojicodes/issues/40

**Comment by gwilku** [comment]
Hi, I'm using .rst

**Comment by gwilku** [comment]
@Peque , not anymore, as it started working.

However I would advise to monitor the situation, because the emojis didn't work when RTD rolled out a hard-block on crashed PDF generation. Now RTD have rolled that change back, and - even though I haven't changed a single thing in my config - the emojis now get replaced as expected.

I only had to add sphinxemoji to requirements.txt and extensions =[] list.
